# -*- coding: utf-8 -*-
"""Ted 12 e 13.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gce4ckvWACoOcnhrWZpfajT5BJI8Qez_

Um dicionário Python pode ser usado para modelar um dicionário de verdade. No entanto, para evitar confusão, chame este dicionário de glossário.
"""

print("GLOSSÁRIO DE PROGRAMAÇÃO\n")

glossario = {'Webscraping': ['Forma de coleta de dados especificos em sites da web'],
             'Google Colab': ['Ambiente em Nuvem que permite escrever e executar códigos em Python no navegador'],
             'Python': ['Linguagem de programação de alto nível e de código aberto lançada em 1991'],
             'Algoritmo': ['Sequencia finita de passos que visam obter a solução de um problema'],
             'Lógica de Programação': ['Organização coerente e estrutural das instruções do algoritmo de programação']}

print('Algoritmo:', glossario['Algoritmo'])
print('\nLógica de Programação:', glossario['Lógica de Programação'])
print('\nPython :', glossario['Python'])
print("\nGoogle Colab : ", glossario['Google Colab'])
print( '\nWebscraping:', glossario['Webscraping'])